Wrote code for the first section
Fiefiez/Portfolio_Sean pull request #1
Opened 2023-01-16 12:34 UTC by Fiefiez

Wrote first section of the codeing challenge. Updated the readme.md file to my credentials

2023-01-16 13:02 UTC, mckent05 reviewed
Hi @Fiefiez, 

# STATUS: INVALID REQUEST ❌ ❌ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that does not have a descriptive enough PR summary and title, please remember that the PR title should summarise the changes made in a PR while the PR summary explains in little more detail what changes were made in the PR
To edit your PR title, open your PR and click on the 'edit' button, reference the picture attached below:
<img width="941" alt="rgwrgwg" src="https://user-images.githubusercontent.com/73607512/204491103-03d8df16-2137-4c39-94e7-f93197a613b3.PNG">

To edit your PR sumary, open your PR and click on the button, reference the picture attached below:
<img width="620" alt="fwhaeth" src="https://user-images.githubusercontent.com/73607512/204491337-71638dde-7add-4d5e-aee9-880c83d55b2a.PNG">

- Please ensure that your readme template is exactly like the [microverse readme](https://github.com/microverseinc/readme-template). Remember having a professional readme helps to make your repo looks professional and tells viewers what your reply is all about

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-16 16:26 UTC, AbayomiOlaoye requested changes
Hi @Fiefiez :wave: , 

Good job, great design in this milestone so far!
There are just a few more issues to work on before moving on to the next project but you are almost there!

![so_close](https://user-images.githubusercontent.com/99715640/211950260-0e3881c0-9d4f-4ea2-a670-9ef45a23a0f5.gif)

## Highlights
- Descriptive Pull Request message :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark: 
- Implemented required changes :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Removing the empty lines I suggested to make your code a lot cleaner
- Making your ReadMe so personalized that it looks like a pitch to recruiters

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 16:26 UTC, AbayomiOlaoye commented on style.css
> +  }
- [ ] You have a really nice design here :clap: , how about adding some spacing element to this hamburger menu so that it doesn't collapse to edge like it currently does? From the Figma design, I think there's a 36px `padding/margin` to the right of your `menu` button. See what I mean :point_down: :point_down: 

![image](https://user-images.githubusercontent.com/99715640/212708673-39975889-558f-4b8d-abaa-62ac9d548f08.png)

2023-01-16 16:26 UTC, AbayomiOlaoye commented on index.html
> +                </a>
- [ ] Sean, did you also notice that this is not supposed to be the link but that the social icons are? That's why I would like to suggest that you change this tag to a `p` tag. It is more semantically right since it's a section of the document that is not linking to other parts. What do you say :grey_question:  :wink:

2023-01-16 16:26 UTC, AbayomiOlaoye commented on index.html
> +                    </li>
- [x] Kindly add descriptive texts to your `alt` attribute in the `img` tags. This is good for accessibility reasons. It allows users of screen readers who are visually impaired to understand the content of your images or in the event of poor connectivity when images cannot be downloaded completely. :wrench:

2023-01-16 16:26 UTC, AbayomiOlaoye commented on style.css
> +}
- [ ] While you have shown great skills and eyes for detail, I do think you have a few things to check in order to complete this project and move on to the next. I have a included a table of images that summarizes some aspects to improve your design below:

|Your Design| Figma Design|
|:--------------:|:-----------------:|
|![image](https://user-images.githubusercontent.com/99715640/212713519-d6e06ae6-ac33-4bca-88d6-9a5b8d6399b0.png)|![image](https://user-images.githubusercontent.com/99715640/212713638-e03dc4eb-a5e1-4f18-bf5c-6c57b4b32127.png)|

2023-01-16 16:26 UTC, AbayomiOlaoye commented on README.md
> +
- I am sorry for this, looks like you were unable to access the source text - and that is why these links are all broken so much that it's not clear to the reader or your site visitor.
- [ ] `ReadMe` file is actually an important part of a project, and it is best if it is readable and descriptive. Kindly access the source files where you have access to [this template](https://github.com/microverseinc/readme-template) that makes your file more descriptive, and please remember to customize it to your project. :notebook: :memo:

2023-01-16 17:39 UTC, Fiefiez commented on style.css
> +  }
Padding and margins are added and has been fixed

2023-01-17 06:15 UTC, Fiefiez commented on index.html
> +                    </li>
I have added the discriptions so it will desplay.

2023-01-17 07:48 UTC, Fiefiez commented on style.css
> +}
This has been changed

2023-01-17 10:03 UTC, wayungi requested changes
Hi @Fiefiez , 

Great work on making the changes requested by a previous reviewer 👏 
![image](https://user-images.githubusercontent.com/99656687/212868220-f881385e-6f95-4db8-9d7a-e76b76f6a9ba.png)

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
 - Descriptive Pull Request message ✔️ 
 - Good use of GitHub flow ✔️ 
 - Meaningful commit messages ✔️ 
 - No linter error ✔️ 
 - Implemented required changes ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 10:03 UTC, wayungi commented on README.md
> +
- [ ] As the previous reviewer requested, please make sure that your `README` file is professional. As it stands now, your `README` does not have marked down. Here is an example of how it should appear and how it is currently appearing
 
 _**How it should appear**_
![readme-pro](https://user-images.githubusercontent.com/99656687/212857905-5d7b7432-2869-4317-adba-3d5ade76ca6a.png)

_**How yours is appearing now**_
![readme-unprof](https://user-images.githubusercontent.com/99656687/212858254-84f04056-f55e-4915-935e-6f56b56b4214.png)

To set up your readme to look professional, please [follow this link](https://github.com/microverseinc/readme-template) and click the file named README.md
![readme guide](https://user-images.githubusercontent.com/99656687/212859795-096eb181-d4c5-4740-a6c5-831ebb9d9993.png)

Then scroll down to the file in the top right corner and click raw, copy all the text in the raw file and paste in your README file then edit it to match your project
![edit](https://user-images.githubusercontent.com/99656687/212860351-8759fd5c-e42c-4462-a8e5-de28f6461ed8.png)

Once the changes are made, scroll down to the bottom of the file and commit the changes. This will save the changes made to your README. it is better to commit after small with meaningful commit messages

2023-01-17 10:03 UTC, wayungi commented on index.html
> +                <div class="logo">My Logo</div>
- [OPTIONAL] It is better to make the logo a link so that when a user clicks on it, it navigates back to the home page. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2023-01-17 12:09 UTC, Fiefiez commented
@wayungi Hi can you please see if all is in order

2023-01-17 13:21 UTC, ghost requested changes
Hi @Fiefiez , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>


## Highlights

✅ Correct use of Github workflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 13:21 UTC, ghost commented on README.md
> +> Describe your project in 1 or 2 sentences.
- [x] Kindly remove these instructions as they are only supposed to guide you on what to fill in your readme file but they should  not appear

2023-01-17 13:21 UTC, ghost commented on README.md
> +</details>
- [x] Kindly on fill the tech-stacks you only used in this project i.e `HTML and CSS`  and remove the ones that were not used

2023-01-17 13:21 UTC, frank1738 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] Kindly include the `key features` of your project

2023-01-17 13:21 UTC, ghost commented on README.md
> +> Describe 1 - 3 features you will add to the project.
- [x] Try as much as you can to customize your readme file with the information available. Kindly include the social links and also ensure the link to your `MIT` license is working

2023-01-17 14:58 UTC, Fiefiez commented
> Hi @Fiefiez ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ![](https://camo.githubusercontent.com/dbedfccef6a814f0329dcd98fd3d0e01dc49e323cce687810ecf26562dcdc776/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966) [ ![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966](https://camo.githubusercontent.com/dbedfccef6a814f0329dcd98fd3d0e01dc49e323cce687810ecf26562dcdc776/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966) ](https://camo.githubusercontent.com/dbedfccef6a814f0329dcd98fd3d0e01dc49e323cce687810ecf26562dcdc776/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966) [ ](https://camo.githubusercontent.com/dbedfccef6a814f0329dcd98fd3d0e01dc49e323cce687810ecf26562dcdc776/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966)
> 
> ## Highlights
> ✅ Correct use of Github workflow ✅ No linter error
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> N/A _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

please have a look if all is in order

2023-01-17 17:26 UTC, Gambit142 requested changes
Hi @Fiefiez 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 17:26 UTC, Gambit142 commented on README.md
> +
- [ ] Just like the former reviewer stated, when I click this link, I am redirected to a 404 error page. Kindly add a valid LICENSE. You can follow the instructions on the right side of the article attached below to set up a valid LICENSE
https://choosealicense.com/licenses/mit/

2023-01-18 07:26 UTC, amejid approved these changes
Hi @Fiefiez, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 07:33 UTC, merged